name: Build ARM64 Runner

on:
  push:
    branches:
      - main
    tags:
      - '*'
  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/spomky-labs/gh-runner
  RUNNER_VERSION: 2.327.1

jobs:
  build:
    name: 🐳 Build Docker (ARM64)
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push image (ARM64)
        run: |
          IMAGE=ghcr.io/spomky-labs/gh-runner
          docker build --build-arg RUNNER_VERSION=2.327.1 -t $IMAGE:latest .
          docker push $IMAGE:latest
