name: Build and Push gh-runner (ARM64)

on:
  push:
    branches: [ main ]
    tags: [ '*' ]
  workflow_dispatch:

env:
  RUNNER_VERSION: 2.327.1

jobs:
  build-arm64:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lowercase owner
        id: vars
        run: echo "owner_lc=${GITHUB_REPOSITORY_OWNER,,}" >> "$GITHUB_OUTPUT"

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image (ARM64)
        run: |
          IMAGE_NAME=ghcr.io/${{ steps.vars.outputs.owner_lc }}/gh-runner
          docker build \
            --build-arg RUNNER_VERSION=${RUNNER_VERSION} \
            --platform linux/arm64 \
            -t $IMAGE_NAME:latest .

      - name: Push image
        run: |
          IMAGE_NAME=ghcr.io/${{ steps.vars.outputs.owner_lc }}/gh-runner
          docker push $IMAGE_NAME:latest
