name: Build and Push gh-runner (ARM64)

on:
  push:
    branches:
      - main
    tags:
      - '*'
  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/spomky-labs/gh-runner
  RUNNER_VERSION: 2.327.1

jobs:
  build:
    name: 🐳 Build Docker (ARM64)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Docker login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        run: |
          IMAGE_TAG="${IMAGE_NAME}:latest"
          echo "Building ${IMAGE_TAG}"
          docker build \
            --build-arg RUNNER_VERSION=${RUNNER_VERSION} \
            --platform linux/arm64 \
            -t ${IMAGE_TAG} \
            .
          docker push ${IMAGE_TAG}
