name: Build and Push gh-runner (ARM64 native)

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}
  RUNNER_VERSION: 2.325.0

jobs:
  prepare:
    name: "🧰 Build Preparation"
    runs-on: ubuntu-latest
    outputs:
      image_name: ${{ steps.normalize.outputs.name }}
      short_sha: ${{ steps.sha.outputs.short }}
    steps:
      - uses: actions/checkout@v4

      - name: Normalize image name
        id: normalize
        run: echo "name=${IMAGE_NAME,,}" >> "$GITHUB_OUTPUT"

      - name: Extract short SHA
        id: sha
        run: echo "short=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

  build-arm64:
    name: "🐳 Build ARM64 image"
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [arm64]
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build image
        run: |
          docker build \
            --build-arg RUNNER_VERSION=${{ env.RUNNER_VERSION }} \
            -t ${{ needs.prepare.outputs.image_name }}:latest \
            -t ${{ needs.prepare.outputs.image_name }}:${{ needs.prepare.outputs.short_sha }} \
            .

      - name: Push image
        run: |
          docker push ${{ needs.prepare.outputs.image_name }}:latest
          docker push ${{ needs.prepare.outputs.image_name }}:${{ needs.prepare.outputs.short_sha }}
